export { default as IndexStartupContainer } from './StartUp';
export { default as SignInContainer } from './SignIn';
export { default as ForgotpasswordContainer } from './Forgotpassword'
export { default as SignUpContainer } from './SignUp';
export { default as DashboardContainer } from './Main/Dashboard';
export { default as WeightBalanceContainer } from './Main/WeightBalance';
export { default as OrdersContainer } from './Main/Orders';
export { default as OrderDetailContainer } from './Main/Orders/Detail';
export { default as NotificationsContainer } from './Main/Notifications';
export { default as AzericardPaymentContainer } from './Main/AzericardPayment';
export { default as PayTRCardListContainer } from './Main/PayTRPayment';
export { default as PayTRPaymentContainer } from './Main/PayTRPayment/Payment';
export { default as PayTRAddCardContainer } from './Main/PayTRPayment/AddCard';
export { default as OthersContainer } from './Main/Others';
export { default as MapContainer } from './Main/Others/MapContainer'
export { default as ExternalAddresses } from './Main/Others/ExternalAddresses';
export { default as TermsOfShipping } from './Main/Others/TermsOfShipping'
export { default as ProfileContainer } from './Main/Others/Profile';
export { default as CourierOrdersContainer } from './Main/Others/CourierOrders';
export { default as NewCourierOrderContainer } from './Main/Others/CourierOrders/NewCourierOrder';
export { default as CourierDeliveryLocation } from './Main/Others/CourierOrders/CourierDeliveryLocation';
export { default as MyOrdersContainer } from './Main/MyOrders/index';
export { default as NewsContainer } from './Main/Others/News';
export { default as InquiryContainer } from './Main/Others/Inquiry'
export { default as NewInquiry } from './Main/Others/Inquiry/NewInquiry'
export { default as NewsDetailContainer } from './Main/Others/News/Detail';
export { default as SelectPackageContainer } from './Main/WeightBalance/SelectPackage';
export { default as BalanceContainer } from './Main/Others/Balance';
export { default as OrderCreateContainer } from './Main/Orders/Create';
export { default as NewOrder } from './Main/MyOrders/NewOrder'

